# Generated by Django 5.1.4 on 2026-07-25 08:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('gullak', 'Gullak'), ('daily_transaction', 'Daily Transaction'), ('savings', 'Savings'), ('revenue_generation', 'Revenue Generation'), ('loan_debt', 'Loan/Debt')], max_length=32)),
                ('account_type', models.CharField(blank=True, help_text="Free text within category, e.g. 'UPI', 'Fixed Deposit'", max_length=50)),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('shared', 'Shared')], default='individual', max_length=16)),
                ('unblock_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Spendable balance, in rupees', max_digits=12)),
                ('block_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saved/blocked balance, in rupees (unused for Gullak itself)', max_digits=12)),
                ('principal', models.DecimalField(blank=True, decimal_places=2, help_text='Original invested amount, in rupees', max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current value, in rupees', max_digits=12, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Rupees; nullable, cards only', max_digits=12, null=True)),
                ('amount_used', models.DecimalField(blank=True, decimal_places=2, help_text='Rupees', max_digits=12, null=True)),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=2, help_text='Rupees', max_digits=12, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('lend', 'Lend'), ('borrow', 'Borrow'), ('gullak_block', 'Gullak Block'), ('gullak_unblock', 'Gullak Unblock')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive, in rupees. Direction is determined by `type`.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('other', 'Other'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('settled', models.BooleanField(default=False, help_text='Lend/borrow only — manually marked settled.')),
                ('client_request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.account')),
                ('transfer_pair', models.ForeignKey(blank=True, help_text='For transfer/gullak_block/gullak_unblock: links the two legs of the same movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'category'], name='wallet_acco_user_id_0e1eae_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'gullak')), fields=('user',), name='one_gullak_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'timestamp'], name='wallet_tran_user_id_a0fc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'timestamp'], name='wallet_tran_account_168a0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('user', 'client_request_id'), name='unique_client_request_per_user'),
        ),
    ]
