# Generated by Django 5.1.4 on 2026-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='owner_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('shared_pair', 'Shared (Relationship)'), ('shared_group', 'Shared (Family & Friends Group)')], default='individual', max_length=16),
        ),
    ]
