# Generated by Django 5.1.4 on 2026-08-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Self-reported UPI ID (e.g. name@bank), used to build settlement pay links. Not verified.', max_length=100, null=True),
        ),
    ]
