# Generated by Django 5.1.4 on 2026-07-25 08:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_link', models.URLField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Rupees', max_digits=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rupees, portion of Gullak assigned to this goal', max_digits=12)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('underfunded', 'Underfunded')], default='on_track', max_length=16)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingGoalDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Rupees still needing to be assigned to a goal's reduced allocation", max_digits=12)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source_transaction', models.ForeignKey(blank=True, help_text='The emergency-unblock leg that caused this overage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_deductions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
