# Generated by Django 5.1.4 on 2026-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='funding_shared_account_id',
            field=models.IntegerField(blank=True, help_text='If set, this goal is a common goal funded only from this shared wallet.Account — never from personal Gullak.', null=True),
        ),
    ]
