from decimal import Decimal

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models

ZERO = Decimal('0.00')


def money_field(**kwargs):
    """Exact decimal rupees, 2 places — same convention as wallet.models.money_field."""
    defaults = dict(max_digits=12, decimal_places=2)
    defaults.update(kwargs)
    return models.DecimalField(**defaults)


class ExpenseSplitType(models.TextChoices):
    EQUAL = 'equal', 'Split equally'
    EXACT = 'exact', 'Exact amounts'


class ExpenseCategory(models.TextChoices):
    FOOD = 'food', 'Food'
    TRAVEL = 'travel', 'Travel'
    ACCOMMODATION = 'accommodation', 'Accommodation'
    SHOPPING = 'shopping', 'Shopping'
    ENTERTAINMENT = 'entertainment', 'Entertainment'
    UTILITIES = 'utilities', 'Utilities'
    OTHER = 'other', 'Other'


class ExpenseEntry(models.Model):
    """
    A single group expense logged against a 'shared_group' wallet.Account (see
    wallet.models.AccountOwnerType.SHARED_GROUP). This is a debt ledger only —
    it never touches the account's pooled block_balance/contributions. Someone
    (the payer) paid `amount` in full; it is then split among `participants`
    according to `split_type`, creating one ExpenseShare row per participant.
    """
    account = models.ForeignKey(
        'wallet.Account', on_delete=models.CASCADE, related_name='expense_entries',
        help_text="Must be a shared_group account; enforced in the serializer/service layer.",
    )
    paid_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='expenses_paid',
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='expenses_logged',
        help_text="Who logged the expense (usually == paid_by, but any member may log on behalf of the payer).",
    )
    description = models.CharField(max_length=200)
    amount = money_field(validators=[MinValueValidator(Decimal('0.01'))])
    category = models.CharField(max_length=20, choices=ExpenseCategory.choices, default=ExpenseCategory.OTHER)
    split_type = models.CharField(max_length=10, choices=ExpenseSplitType.choices, default=ExpenseSplitType.EQUAL)
    expense_date = models.DateField()
    note = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-expense_date', '-created_at']
        indexes = [models.Index(fields=['account', 'expense_date'])]

    def __str__(self):
        return f"{self.description} (₹{self.amount}) in {self.account}"

    def clean(self):
        if self.account_id and not self.account.owner_type == 'shared_group':
            raise ValidationError({'account': 'Expense splitting is only available for Family & Friends group accounts.'})


class ExpenseShare(models.Model):
    """
    One participant's share of an ExpenseEntry. Sum of all shares for an entry
    must equal the entry's amount (validated at the service layer on creation).
    The payer also gets a share row (they owe their own portion too — the net
    effect is computed later by the settlement engine from all shares + who paid).
    """
    expense = models.ForeignKey(ExpenseEntry, on_delete=models.CASCADE, related_name='shares')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='expense_shares')
    share_amount = money_field(validators=[MinValueValidator(Decimal('0.00'))])

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['expense', 'user'], name='unique_share_per_expense_user')
        ]

    def __str__(self):
        return f"{self.user} owes ₹{self.share_amount} for {self.expense}"


class SettlementStatus(models.TextChoices):
    PENDING = 'pending', 'Pending'
    PAID = 'paid', 'Paid'


class Settlement(models.Model):
    """
    A simplified 'who owes whom' record for a group account, generated by
    expenses.services.generate_settlements() from the current unsettled
    ExpenseShare balances. Regenerating settlements replaces all PENDING
    settlements for the account (PAID ones are kept as history).

    Marking as paid is a manual confirmation by the payee (receiver) — no real
    money moves; this mirrors the rest of Gullak's no-payment-gateway design.
    A UPI deep-link is provided so the payer can open their UPI app pre-filled.
    """
    account = models.ForeignKey('wallet.Account', on_delete=models.CASCADE, related_name='settlements')
    payer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='settlements_to_pay',
        help_text="The member who owes money.",
    )
    payee = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='settlements_to_receive',
        help_text="The member who is owed money.",
    )
    amount = money_field(validators=[MinValueValidator(Decimal('0.01'))])
    status = models.CharField(max_length=10, choices=SettlementStatus.choices, default=SettlementStatus.PENDING)
    generated_at = models.DateTimeField(auto_now_add=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    marked_paid_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='+',
    )

    class Meta:
        ordering = ['-generated_at']
        indexes = [models.Index(fields=['account', 'status'])]

    def __str__(self):
        return f"{self.payer} owes {self.payee} ₹{self.amount} ({self.status})"

    @property
    def upi_link(self):
        """UPI deep-link to pay the payee, using the payee's self-reported UPI ID (if set)."""
        payee_upi = getattr(self.payee, 'upi_id', '') or ''
        if not payee_upi:
            return None
        payee_name = self.payee.get_full_name() or self.payee.username
        note = f"Gullak settlement - {self.account.name}"
        return (
            f"upi://pay?pa={payee_upi}&pn={payee_name}&am={self.amount}"
            f"&cu=INR&tn={note}"
        ).replace(' ', '%20')
