# Generated by Django 5.1.4 on 2026-08-08 02:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0002_alter_account_owner_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('accommodation', 'Accommodation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=20)),
                ('split_type', models.CharField(choices=[('equal', 'Split equally'), ('exact', 'Exact amounts')], default='equal', max_length=10)),
                ('expense_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Must be a shared_group account; enforced in the serializer/service layer.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='wallet.account')),
                ('created_by', models.ForeignKey(help_text='Who logged the expense (usually == paid_by, but any member may log on behalf of the payer).', on_delete=django.db.models.deletion.CASCADE, related_name='expenses_logged', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.expenseentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='wallet.account')),
                ('marked_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(help_text='The member who is owed money.', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_to_receive', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(help_text='The member who owes money.', on_delete=django.db.models.deletion.CASCADE, related_name='settlements_to_pay', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['account', 'expense_date'], name='expenses_ex_account_4c4fe2_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseshare',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='unique_share_per_expense_user'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['account', 'status'], name='expenses_se_account_e4e97a_idx'),
        ),
    ]
