# Generated by Django 5.1.4 on 2026-08-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invite', 'Invite'), ('admin_transfer', 'Admin Transfer'), ('reminder', 'Reminder'), ('goal_underfunded', 'Goal Underfunded'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('admin_changed', 'Admin Changed'), ('settlement_paid', 'Settlement Paid')], max_length=32),
        ),
    ]
